modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="op_generators_"
version="Beta 1.0.0"
displayName="Op Generators 2 The Spark Of Tech"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Beardogmoddingco---curseforge account beardog122112"
description='''
adds new generators that output RF also known as RF
'''

[[dependencies.op_generators_]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




